name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployed artifact
        required: false
        default: dist
        type: string
      secret:
        some-secret:
          required: false
      outputs:
        result:
          description: The result of the deployment operation
          value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  outputs:
    outcome: ${{ steps.set-result.output.step-result }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name:: ${{ inputs.artifact-name }}
      - name: Output Information
        run: echo "Deploying and Uploading..."
      - name: Set Output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
